services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432" # local port:container port
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d orders_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - ecommerce-microservices-network

volumes:
  postgres_data:

networks:
  ecommerce-microservices-network:
    driver: bridge
